### ISSUE TITLE
Niramit : 200 and 700

### ISSUE THREAD

**Issue by Thanarat-Vachiruckul** [cadsondemak/Niramit#4]
Latin 200 and 700

![screen shot 2018-05-15 at 12 36 26 pm](https://user-images.githubusercontent.com/35482151/40038665-8d51ac72-583d-11e8-9f52-64cccff89030.png)

![screen shot 2018-05-15 at 12 36 14 pm](https://user-images.githubusercontent.com/35482151/40038674-954c8d34-583d-11e8-936b-488ef4341790.png)

Thai 200 and 700

![screen shot 2018-05-15 at 12 39 56 pm](https://user-images.githubusercontent.com/35482151/40038685-a0e68ee2-583d-11e8-86eb-4a9a450da067.png)

![screen shot 2018-05-15 at 12 40 03 pm](https://user-images.githubusercontent.com/35482151/40038688-a62186aa-583d-11e8-8358-8a1f8adc9399.png)

**Comment by davelab6** [comment]
Anuthin and I discussed this and he proposed making the ‘n’ ‘m’ ‘h’ have less bounce in the lowercase bold
