### ISSUE TITLE
Revert back to f4aee53721f234c34bb7f6bfec479da0864c6a5c

### ISSUE THREAD

**Issue by m4rc1e** [cadsondemak/Niramit#7]
The source files won't open for this project because it contains merge conflicts, https://github.com/cadsondemak/Niramit/commit/efc6978345122bcfab17ee1f1f9621b6160bd027#r30677671

Please revert back to my last pr, f4aee53721f234c34bb7f6bfec479da0864c6a5c

**Comment by cadsondemakoffice** [comment]
Sorry, now revert back to f4aee53. Thank you.

**Comment by m4rc1e** [comment]
Repull the repo locally and see if you can open the .glyphs file in github ;-)

**Comment by cadsondemakoffice** [comment]
Yeah, Now I can open the .glyphs file !!  :-D

**Comment by davelab6** [comment]
Can this issue be closed?

**Comment by m4rc1e** [comment]
Yep. Closing
